import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Acceptable Use Policy - CaseBreak AI",
  description: "CaseBreak AI Acceptable Use Policy and Unauthorized Practice of Law disclaimer.",
}

export default function AcceptableUsePage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b" id="aup-header">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="text-2xl font-bold text-blue-900">CaseBreak.AI</Link>
            <nav className="hidden md:flex items-center space-x-8">
              <Link href="/about" className="text-gray-600 hover:text-gray-900">About</Link>
              <Link href="/features" className="text-gray-600 hover:text-gray-900">Features</Link>
              <Link href="/pricing" className="text-gray-600 hover:text-gray-900">Pricing</Link>
              <Link href="/contact" className="text-gray-600 hover:text-gray-900">Contact</Link>
              <Link href="/sign-up" className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">Get Started</Link>
            </nav>
          </div>
        </div>
      </header>
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto prose prose-slate">
          <h1 id="aup-title">Acceptable Use Policy</h1>
          <p className="text-sm text-gray-500">Effective Date: March 20, 2026</p>

          <h2>Permitted Uses</h2>
          <p>CaseBreak AI is designed for legal professionals analyzing case data, law firms conducting research, healthcare providers assessing compliance risk, and compliance officers monitoring regulatory risk.</p>

          <h2>Prohibited Uses</h2>
          <p>You may not use the Service to: engage in unlawful activity, provide legal advice to third parties without licensure, represent AI outputs as certified legal opinions, upload data without legal basis, reverse-engineer training data, introduce malware, or generate fraudulent documents.</p>

          <h2>Enforcement</h2>
          <p>Violations may result in warning, suspension, termination, or reporting to authorities. Contact abuse@casebreak.ai to report violations.</p>

          <hr className="my-12" />

          <h1 id="upl-disclaimer">Legal Disclaimer &mdash; Unauthorized Practice of Law</h1>
          <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg not-prose">
            <p className="text-lg font-bold text-amber-900 mb-4">CaseBreak AI is NOT a law firm. CaseBreak AI is NOT a lawyer. CaseBreak AI does NOT provide legal advice.</p>
            <p className="text-amber-800 mb-3">All features, outputs, and communications generated by CaseBreak AI are informational tools designed to assist qualified legal professionals. They are not legal advice.</p>
            <p className="text-amber-800 mb-3"><strong>If you are a licensed attorney:</strong> CaseBreak AI supplements&mdash;not replaces&mdash;your professional judgment. You remain solely responsible for all legal advice you provide.</p>
            <p className="text-amber-800 mb-3"><strong>If you are not a licensed attorney:</strong> You may NOT use CaseBreak AI outputs to provide legal advice to others or represent yourself as providing legal services.</p>
            <p className="text-amber-800"><strong>No attorney-client relationship</strong> is created by use of this Service. No privilege, confidentiality, or fiduciary duty arises from your use.</p>
          </div>

          <p className="text-sm text-gray-500 mt-12 border-t pt-4">This document is for informational purposes. Consult a qualified attorney for legal advice specific to your situation.</p>
        </div>
      </main>
    </div>
  )
}
