'use client'

import { useState } from 'react'
import { AlertTriangle, X, ExternalLink } from 'lucide-react'

interface AIDisclosureBannerProps {
  /** Whether the banner can be dismissed (default: false for legal compliance) */
  dismissible?: boolean
  /** Compact mode for inline use */
  compact?: boolean
}

/**
 * Utah SB 226 (AICPA) AI Disclosure Banner
 *
 * Required for compliance with Utah's Artificial Intelligence Policy Act.
 * This banner must be prominently displayed during all AI-assisted interactions
 * to inform users that they are interacting with AI-generated content.
 *
 * Reference: Utah Code 13-62 (Artificial Intelligence Policy Act)
 */
export function AIDisclosureBanner({
  dismissible = false,
  compact = false
}: AIDisclosureBannerProps) {
  const [dismissed, setDismissed] = useState(false)

  if (dismissed && dismissible) {
    return null
  }

  if (compact) {
    return (
      <div className="flex items-center gap-2 px-3 py-1.5 bg-amber-500/10 border border-amber-500/20 rounded-md text-amber-200 text-xs">
        <AlertTriangle className="w-3 h-3 flex-shrink-0" />
        <span>
          <strong>AI Disclosure:</strong> Content generated by artificial intelligence. Not legal advice.
        </span>
      </div>
    )
  }

  return (
    <div className="relative bg-gradient-to-r from-amber-900/30 to-amber-800/20 border-b border-amber-500/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3">
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0 mt-0.5">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
          </div>

          <div className="flex-1 min-w-0">
            <p className="text-sm text-amber-100 font-medium">
              AI-Generated Content Disclosure (Utah SB 226)
            </p>
            <p className="mt-1 text-xs text-amber-200/80 leading-relaxed">
              This platform uses artificial intelligence to simulate legal proceedings for
              educational and preparation purposes only. All AI-generated responses, arguments,
              and rulings are simulations and do not constitute legal advice. Users must
              independently verify all information and consult with licensed attorneys for
              actual legal matters.
            </p>
            <div className="mt-2 flex items-center gap-4">
              <a
                href="https://le.utah.gov/~2024/bills/static/SB0226.html"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 text-xs text-amber-300 hover:text-amber-200 underline underline-offset-2"
              >
                View Utah SB 226
                <ExternalLink className="w-3 h-3" />
              </a>
              <span className="text-xs text-amber-400/60">
                Effective: May 1, 2024
              </span>
            </div>
          </div>

          {dismissible && (
            <button
              onClick={() => setDismissed(true)}
              className="flex-shrink-0 p-1 rounded hover:bg-amber-500/20 text-amber-400 hover:text-amber-300 transition-colors"
              aria-label="Dismiss disclosure"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

/**
 * Inline AI disclosure for individual messages/responses
 */
export function AIDisclosureInline() {
  return (
    <div className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-slate-700/50 rounded text-xs text-slate-400">
      <AlertTriangle className="w-3 h-3" />
      <span>AI-generated response</span>
    </div>
  )
}

/**
 * Footer disclosure for documents/exports
 */
export function AIDisclosureFooter() {
  return (
    <div className="mt-8 pt-4 border-t border-slate-700">
      <p className="text-xs text-slate-500 leading-relaxed">
        <strong className="text-slate-400">AI Disclosure (Utah SB 226):</strong> This document
        was generated using artificial intelligence technology. The content is provided for
        educational and simulation purposes only and does not constitute legal advice. All
        information should be independently verified by a licensed attorney before use in
        actual legal proceedings. CaseCraft and its AI systems are not substitutes for
        professional legal counsel.
      </p>
    </div>
  )
}
