import { jsPDF } from 'jspdf'
import type { Case, Agent, Document, CaseFact, AgentRole, DocumentType, CaseType, FactCategory } from '@/lib/types'

interface CaseReportPDFOptions {
  caseData: Case
  agents?: Agent[]
  documents?: Document[]
  facts?: CaseFact[]
}

const TYPE_LABELS: Record<CaseType, string> = {
  civil: 'Civil',
  criminal: 'Criminal',
  family: 'Family Law',
  contract: 'Contract',
  tort: 'Tort',
  property: 'Property',
  constitutional: 'Constitutional',
  administrative: 'Administrative',
}

const ROLE_DISPLAY_NAMES: Record<AgentRole, string> = {
  judge: 'Presiding Judge',
  plaintiff_attorney: 'Plaintiff\'s Attorney',
  defense_attorney: 'Defense Attorney',
  court_clerk: 'Court Clerk',
  witness: 'Witness',
  expert_witness: 'Expert Witness',
  mediator: 'Mediator',
  law_clerk: 'Law Clerk',
  county_recorder: 'County Recorder',
  dogm_agent: 'DOGM Agent',
}

const DOC_TYPE_LABELS: Record<DocumentType, string> = {
  complaint: 'Complaint',
  answer: 'Answer',
  motion: 'Motion',
  brief: 'Brief',
  discovery: 'Discovery',
  deposition: 'Deposition',
  exhibit: 'Exhibit',
  order: 'Order',
  judgment: 'Judgment',
  other: 'Other',
}

const FACT_CATEGORY_LABELS: Record<FactCategory, string> = {
  undisputed: 'Undisputed Fact',
  disputed: 'Disputed Fact',
  evidence_based: 'Evidence-Based',
  testimony: 'Testimony',
  expert_opinion: 'Expert Opinion',
  stipulated: 'Stipulated Fact',
}

/**
 * Generates a professional PDF case report
 */
export function generateCaseReportPDF(options: CaseReportPDFOptions): void {
  const { caseData, agents = [], documents = [], facts = [] } = options

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 72 // 1 inch margin
  const contentWidth = pageWidth - margin * 2
  const lineHeight = 14
  let yPos = margin

  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  // Helper function to add a new page
  const addNewPage = () => {
    doc.addPage()
    yPos = margin
    addFooter()
  }

  // Helper function to check if we need a new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin - 30) {
      addNewPage()
      return true
    }
    return false
  }

  // Helper function to add footer
  const addFooter = () => {
    const pageNumber = doc.getNumberOfPages()
    doc.setFontSize(9)
    doc.setFont('times', 'normal')
    doc.setTextColor(100, 100, 100)

    doc.text(
      `Page ${pageNumber}`,
      pageWidth / 2,
      pageHeight - 30,
      { align: 'center' }
    )

    doc.text(
      'Generated by CaseCraft Legal Simulation Platform',
      pageWidth / 2,
      pageHeight - 18,
      { align: 'center' }
    )

    doc.setTextColor(0, 0, 0)
  }

  // Helper function to wrap text
  const wrapText = (text: string, maxWidth: number, fontSize: number): string[] => {
    doc.setFontSize(fontSize)
    const words = text.split(' ')
    const lines: string[] = []
    let currentLine = ''

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word
      const testWidth = doc.getTextWidth(testLine)

      if (testWidth > maxWidth && currentLine) {
        lines.push(currentLine)
        currentLine = word
      } else {
        currentLine = testLine
      }
    }

    if (currentLine) {
      lines.push(currentLine)
    }

    return lines
  }

  // Helper to add section header
  const addSectionHeader = (title: string) => {
    checkPageBreak(50)
    yPos += 10
    doc.setFont('times', 'bold')
    doc.setFontSize(13)
    doc.text(title.toUpperCase(), margin, yPos)
    yPos += 8
    doc.setLineWidth(1)
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 16
  }

  // Helper to add field row
  const addFieldRow = (label: string, value: string, indent = 0) => {
    checkPageBreak(lineHeight * 2)
    doc.setFont('times', 'bold')
    doc.setFontSize(11)
    doc.text(`${label}:`, margin + indent, yPos)
    doc.setFont('times', 'normal')

    const labelWidth = doc.getTextWidth(`${label}: `)
    const valueMaxWidth = contentWidth - indent - labelWidth - 20
    const valueLines = wrapText(value || 'N/A', valueMaxWidth, 11)

    valueLines.forEach((line, index) => {
      if (index === 0) {
        doc.text(line, margin + indent + labelWidth, yPos)
      } else {
        yPos += lineHeight
        checkPageBreak(lineHeight)
        doc.text(line, margin + indent + labelWidth, yPos)
      }
    })
    yPos += lineHeight + 4
  }

  // ====== COVER PAGE / HEADER ======

  doc.setFont('times', 'bold')
  doc.setFontSize(18)
  doc.text('CASE REPORT', pageWidth / 2, yPos, { align: 'center' })
  yPos += 28

  doc.setFontSize(12)
  doc.text('CONFIDENTIAL - FOR SIMULATION PURPOSES ONLY', pageWidth / 2, yPos, { align: 'center' })
  yPos += 32

  // Horizontal rule
  doc.setLineWidth(2)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 24

  // Case title
  if (caseData.plaintiff_name && caseData.defendant_name) {
    doc.setFont('times', 'bold')
    doc.setFontSize(14)
    doc.text(caseData.plaintiff_name.toUpperCase(), pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight + 2
    doc.setFont('times', 'italic')
    doc.setFontSize(12)
    doc.text('v.', pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight + 2
    doc.setFont('times', 'bold')
    doc.setFontSize(14)
    doc.text(caseData.defendant_name.toUpperCase(), pageWidth / 2, yPos, { align: 'center' })
    yPos += 20
  } else {
    doc.setFont('times', 'bold')
    doc.setFontSize(14)
    const titleLines = wrapText(caseData.name.toUpperCase(), contentWidth, 14)
    titleLines.forEach((line) => {
      doc.text(line, pageWidth / 2, yPos, { align: 'center' })
      yPos += lineHeight + 2
    })
    yPos += 10
  }

  // Case number
  doc.setFont('times', 'normal')
  doc.setFontSize(12)
  if (caseData.case_number) {
    doc.text(`Case No.: ${caseData.case_number}`, pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight + 4
  }

  doc.text(`Report Generated: ${dateStr}`, pageWidth / 2, yPos, { align: 'center' })
  yPos += 28

  // Horizontal rule
  doc.setLineWidth(1)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 24

  // Add footer to first page
  addFooter()

  // ====== CASE SUMMARY SECTION ======

  addSectionHeader('Case Summary')

  if (caseData.summary) {
    doc.setFont('times', 'normal')
    doc.setFontSize(11)
    const summaryLines = wrapText(caseData.summary, contentWidth - 20, 11)
    summaryLines.forEach((line) => {
      checkPageBreak(lineHeight)
      doc.text(line, margin + 10, yPos)
      yPos += lineHeight
    })
    yPos += 10
  } else {
    doc.setFont('times', 'italic')
    doc.setFontSize(11)
    doc.text('No summary provided.', margin + 10, yPos)
    yPos += lineHeight + 10
  }

  // ====== PARTIES INVOLVED SECTION ======

  addSectionHeader('Parties Involved')

  if (caseData.plaintiff_name) {
    addFieldRow('Plaintiff', caseData.plaintiff_name, 10)
  }
  if (caseData.defendant_name) {
    addFieldRow('Defendant', caseData.defendant_name, 10)
  }
  if (!caseData.plaintiff_name && !caseData.defendant_name) {
    doc.setFont('times', 'italic')
    doc.setFontSize(11)
    doc.text('No parties specified.', margin + 10, yPos)
    yPos += lineHeight
  }

  // ====== CASE DETAILS SECTION ======

  addSectionHeader('Case Details')

  addFieldRow('Case Type', TYPE_LABELS[caseData.case_type as CaseType] || caseData.case_type, 10)
  addFieldRow('Status', caseData.status.charAt(0).toUpperCase() + caseData.status.slice(1), 10)
  addFieldRow('Jurisdiction', caseData.jurisdiction || 'Not specified', 10)
  addFieldRow('Filed Date', caseData.filed_date || 'Not filed', 10)
  addFieldRow('Created', new Date(caseData.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }), 10)

  // ====== KEY FACTS SECTION ======

  if (facts.length > 0) {
    addSectionHeader(`Key Facts (${facts.length})`)

    // Group facts by category
    const factsByCategory = facts.reduce((acc, fact) => {
      const category = fact.category || 'other'
      if (!acc[category]) acc[category] = []
      acc[category].push(fact)
      return acc
    }, {} as Record<string, CaseFact[]>)

    Object.entries(factsByCategory).forEach(([category, categoryFacts]) => {
      checkPageBreak(40)
      doc.setFont('times', 'bold')
      doc.setFontSize(11)
      const categoryLabel = FACT_CATEGORY_LABELS[category as FactCategory] || category
      doc.text(`${categoryLabel}:`, margin + 10, yPos)
      yPos += lineHeight + 4

      categoryFacts.forEach((fact, index) => {
        const disputedMarker = fact.is_disputed ? ' [DISPUTED]' : ''
        const factText = `${index + 1}. ${fact.fact_text}${disputedMarker}`
        const factLines = wrapText(factText, contentWidth - 40, 11)

        doc.setFont('times', 'normal')
        doc.setFontSize(11)

        factLines.forEach((line) => {
          checkPageBreak(lineHeight)
          doc.text(line, margin + 20, yPos)
          yPos += lineHeight
        })
        yPos += 4
      })

      yPos += 8
    })
  }

  // ====== AGENT CONFIGURATIONS SECTION ======

  if (agents.length > 0) {
    addSectionHeader(`Agent Configurations (${agents.length})`)

    agents.forEach((agent, index) => {
      const entryHeight = 60 + (agent.persona_prompt ? Math.ceil(agent.persona_prompt.length / 80) * lineHeight : 0)
      checkPageBreak(entryHeight)

      doc.setFont('times', 'bold')
      doc.setFontSize(11)
      const roleLabel = ROLE_DISPLAY_NAMES[agent.role as AgentRole] || agent.role.replace(/_/g, ' ')
      doc.text(`${index + 1}. ${agent.name}`, margin + 10, yPos)

      doc.setFont('times', 'italic')
      const statusText = agent.is_active ? '(Active)' : '(Inactive)'
      doc.text(` - ${roleLabel} ${statusText}`, margin + 10 + doc.getTextWidth(`${index + 1}. ${agent.name}`), yPos)
      yPos += lineHeight + 4

      doc.setFont('times', 'normal')
      doc.setFontSize(10)

      // Temperature
      doc.text(`Temperature: ${agent.temperature}`, margin + 20, yPos)
      yPos += lineHeight

      // Persona (truncated if too long)
      if (agent.persona_prompt) {
        const personaPreview = agent.persona_prompt.length > 300
          ? agent.persona_prompt.slice(0, 297) + '...'
          : agent.persona_prompt
        const personaLines = wrapText(`Persona: ${personaPreview}`, contentWidth - 40, 10)
        personaLines.forEach((line) => {
          checkPageBreak(lineHeight)
          doc.text(line, margin + 20, yPos)
          yPos += lineHeight - 2
        })
      }

      yPos += 10

      // Separator between agents
      if (index < agents.length - 1) {
        doc.setDrawColor(200, 200, 200)
        doc.setLineWidth(0.5)
        doc.line(margin + 30, yPos - 5, pageWidth - margin - 30, yPos - 5)
        doc.setDrawColor(0, 0, 0)
      }
    })
  }

  // ====== DOCUMENTS SECTION ======

  if (documents.length > 0) {
    addSectionHeader(`Documents (${documents.length})`)

    // Group documents by type
    const docsByType = documents.reduce((acc, doc) => {
      const type = doc.doc_type || 'other'
      if (!acc[type]) acc[type] = []
      acc[type].push(doc)
      return acc
    }, {} as Record<string, Document[]>)

    Object.entries(docsByType).forEach(([type, typeDocs]) => {
      checkPageBreak(40)
      doc.setFont('times', 'bold')
      doc.setFontSize(11)
      const typeLabel = DOC_TYPE_LABELS[type as DocumentType] || type
      doc.text(`${typeLabel}s (${typeDocs.length}):`, margin + 10, yPos)
      yPos += lineHeight + 4

      typeDocs.forEach((document, index) => {
        checkPageBreak(lineHeight * 2)
        doc.setFont('times', 'normal')
        doc.setFontSize(10)

        const embeddedStatus = document.is_embedded ? '[Embedded]' : ''
        const fileSizeStr = document.file_size
          ? `(${(document.file_size / 1024).toFixed(1)} KB)`
          : ''

        doc.text(
          `${index + 1}. ${document.name} ${fileSizeStr} ${embeddedStatus}`,
          margin + 20,
          yPos
        )
        yPos += lineHeight + 2
      })

      yPos += 8
    })
  }

  // ====== FOOTER NOTE ======

  yPos += 20
  checkPageBreak(80)

  doc.setLineWidth(1)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 20

  doc.setFont('times', 'bold')
  doc.setFontSize(11)
  doc.text('DISCLAIMER', pageWidth / 2, yPos, { align: 'center' })
  yPos += 16

  doc.setFont('times', 'italic')
  doc.setFontSize(9)
  const disclaimer = 'This case report was generated by CaseCraft, an AI-powered legal simulation platform. ' +
    'This document is intended for educational, training, and simulation purposes only. ' +
    'It does not constitute legal advice and should not be used in actual legal proceedings.'

  const disclaimerLines = wrapText(disclaimer, contentWidth - 40, 9)
  disclaimerLines.forEach((line) => {
    checkPageBreak(lineHeight - 2)
    doc.text(line, pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight - 2
  })

  // Update footer on last page
  addFooter()

  // Generate filename and download
  const sanitizedCaseName = caseData.name.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  const timestampSlug = now.toISOString().replace(/[:.]/g, '-')
  const filename = `case_report_${sanitizedCaseName}_${timestampSlug}.pdf`

  doc.save(filename)
}
