import { jsPDF } from 'jspdf'
import type { AgentRole } from '@/lib/types'

interface HearingTurn {
  role: AgentRole
  agentId: string
  agentName: string
  content: string
  phase: string
  timestamp: string
}

interface TranscriptPDFOptions {
  caseName: string
  caseNumber?: string
  hearingType: string
  transcript: HearingTurn[]
  jurisdiction?: string
  plaintiffName?: string
  defendantName?: string
}

const ROLE_DISPLAY_NAMES: Record<AgentRole, string> = {
  judge: 'Presiding Judge',
  plaintiff_attorney: 'Plaintiff\'s Attorney',
  defense_attorney: 'Defense Attorney',
  court_clerk: 'Court Clerk',
  witness: 'Witness',
  expert_witness: 'Expert Witness',
  mediator: 'Mediator',
  law_clerk: 'Law Clerk',
  county_recorder: 'County Recorder',
  dogm_agent: 'DOGM Agent',
}

/**
 * Generates a professional PDF transcript of a mock hearing
 */
export function generateTranscriptPDF(options: TranscriptPDFOptions): void {
  const {
    caseName,
    caseNumber,
    hearingType,
    transcript,
    jurisdiction,
    plaintiffName,
    defendantName,
  } = options

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 72 // 1 inch margin
  const contentWidth = pageWidth - margin * 2
  const lineHeight = 14
  let yPos = margin

  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const timeStr = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })

  // Helper function to add a new page
  const addNewPage = () => {
    doc.addPage()
    yPos = margin
    addFooter()
  }

  // Helper function to check if we need a new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin - 30) {
      addNewPage()
      return true
    }
    return false
  }

  // Helper function to add footer
  const addFooter = () => {
    const pageNumber = doc.getNumberOfPages()
    doc.setFontSize(9)
    doc.setFont('times', 'normal')
    doc.setTextColor(100, 100, 100)

    // Page number
    doc.text(
      `Page ${pageNumber}`,
      pageWidth / 2,
      pageHeight - 30,
      { align: 'center' }
    )

    // Generated by text
    doc.text(
      'Generated by CaseCraft Legal Simulation Platform',
      pageWidth / 2,
      pageHeight - 18,
      { align: 'center' }
    )

    doc.setTextColor(0, 0, 0)
  }

  // Helper function to wrap text
  const wrapText = (text: string, maxWidth: number, fontSize: number): string[] => {
    doc.setFontSize(fontSize)
    const words = text.split(' ')
    const lines: string[] = []
    let currentLine = ''

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word
      const testWidth = doc.getTextWidth(testLine)

      if (testWidth > maxWidth && currentLine) {
        lines.push(currentLine)
        currentLine = word
      } else {
        currentLine = testLine
      }
    }

    if (currentLine) {
      lines.push(currentLine)
    }

    return lines
  }

  // ====== COVER PAGE / HEADER ======

  // Title - Centered
  doc.setFont('times', 'bold')
  doc.setFontSize(16)
  doc.text('OFFICIAL TRANSCRIPT', pageWidth / 2, yPos, { align: 'center' })
  yPos += 24

  doc.setFontSize(14)
  doc.text('MOCK HEARING PROCEEDINGS', pageWidth / 2, yPos, { align: 'center' })
  yPos += 36

  // Horizontal rule
  doc.setLineWidth(1)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 24

  // Case information
  doc.setFont('times', 'bold')
  doc.setFontSize(12)

  if (plaintiffName && defendantName) {
    doc.text(`${plaintiffName.toUpperCase()}`, pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight
    doc.setFont('times', 'italic')
    doc.text('v.', pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight
    doc.setFont('times', 'bold')
    doc.text(`${defendantName.toUpperCase()}`, pageWidth / 2, yPos, { align: 'center' })
    yPos += 24
  } else {
    const caseTitleLines = wrapText(caseName.toUpperCase(), contentWidth, 12)
    caseTitleLines.forEach((line) => {
      doc.text(line, pageWidth / 2, yPos, { align: 'center' })
      yPos += lineHeight
    })
    yPos += 10
  }

  // Case number and hearing type
  doc.setFont('times', 'normal')
  doc.setFontSize(11)

  if (caseNumber) {
    doc.text(`Case No.: ${caseNumber}`, pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight
  }

  const hearingTypeFormatted = hearingType
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())

  doc.text(`Hearing Type: ${hearingTypeFormatted}`, pageWidth / 2, yPos, { align: 'center' })
  yPos += lineHeight

  if (jurisdiction) {
    doc.text(`Jurisdiction: ${jurisdiction}`, pageWidth / 2, yPos, { align: 'center' })
    yPos += lineHeight
  }

  yPos += 10

  doc.text(`Date: ${dateStr}`, pageWidth / 2, yPos, { align: 'center' })
  yPos += lineHeight
  doc.text(`Time: ${timeStr}`, pageWidth / 2, yPos, { align: 'center' })
  yPos += 24

  // Horizontal rule
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 24

  // ====== APPEARANCES ======

  doc.setFont('times', 'bold')
  doc.setFontSize(12)
  doc.text('APPEARANCES:', margin, yPos)
  yPos += 20

  doc.setFont('times', 'normal')
  doc.setFontSize(11)

  // Get unique speakers
  const speakers = new Map<string, { name: string; role: AgentRole }>()
  transcript.forEach((turn) => {
    if (!speakers.has(turn.agentId)) {
      speakers.set(turn.agentId, { name: turn.agentName, role: turn.role })
    }
  })

  speakers.forEach((speaker) => {
    checkPageBreak(lineHeight * 2)
    const roleDisplay = ROLE_DISPLAY_NAMES[speaker.role] || speaker.role.replace(/_/g, ' ')
    doc.text(`${speaker.name}`, margin + 20, yPos)
    doc.setFont('times', 'italic')
    doc.text(`  - ${roleDisplay}`, margin + 20 + doc.getTextWidth(speaker.name), yPos)
    doc.setFont('times', 'normal')
    yPos += lineHeight + 4
  })

  yPos += 20

  // Horizontal rule
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 24

  // Add footer to first page
  addFooter()

  // ====== PROCEEDINGS ======

  doc.setFont('times', 'bold')
  doc.setFontSize(12)
  doc.text('PROCEEDINGS', margin, yPos)
  yPos += 24

  // Transcript entries
  transcript.forEach((turn, index) => {
    // Calculate space needed for this entry
    const contentLines = wrapText(turn.content, contentWidth - 40, 11)
    const entryHeight = lineHeight * (contentLines.length + 3)

    checkPageBreak(entryHeight)

    // Timestamp and speaker
    const time = new Date(turn.timestamp).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    })

    const phaseFormatted = turn.phase.replace(/_/g, ' ').toUpperCase()

    doc.setFont('times', 'bold')
    doc.setFontSize(11)
    doc.text(`[${time}]`, margin, yPos)

    const speakerX = margin + doc.getTextWidth(`[${time}]  `)
    doc.text(turn.agentName.toUpperCase(), speakerX, yPos)

    doc.setFont('times', 'italic')
    doc.setFontSize(10)
    const roleDisplay = ROLE_DISPLAY_NAMES[turn.role] || turn.role.replace(/_/g, ' ')
    doc.text(` (${roleDisplay} - ${phaseFormatted}):`, speakerX + doc.getTextWidth(turn.agentName.toUpperCase()), yPos)

    yPos += lineHeight + 4

    // Content
    doc.setFont('times', 'normal')
    doc.setFontSize(11)

    contentLines.forEach((line) => {
      checkPageBreak(lineHeight)
      doc.text(line, margin + 20, yPos)
      yPos += lineHeight
    })

    yPos += 12

    // Light separator between entries (not on last entry)
    if (index < transcript.length - 1) {
      doc.setDrawColor(200, 200, 200)
      doc.setLineWidth(0.5)
      doc.line(margin + 40, yPos - 6, pageWidth - margin - 40, yPos - 6)
      doc.setDrawColor(0, 0, 0)
      doc.setLineWidth(1)
    }
  })

  // ====== END OF TRANSCRIPT ======

  yPos += 20
  checkPageBreak(80)

  doc.setLineWidth(1)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 20

  doc.setFont('times', 'bold')
  doc.setFontSize(12)
  doc.text('END OF TRANSCRIPT', pageWidth / 2, yPos, { align: 'center' })
  yPos += 24

  doc.setFont('times', 'italic')
  doc.setFontSize(10)
  doc.text(
    'This transcript was generated by CaseCraft AI Legal Simulation Platform.',
    pageWidth / 2,
    yPos,
    { align: 'center' }
  )
  yPos += lineHeight
  doc.text(
    'This document is for educational and simulation purposes only.',
    pageWidth / 2,
    yPos,
    { align: 'center' }
  )

  // Update footer on last page
  addFooter()

  // Generate filename and download
  const sanitizedCaseName = caseName.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  const dateSlug = now.toISOString().split('T')[0]
  const filename = `transcript_${sanitizedCaseName}_${dateSlug}.pdf`

  doc.save(filename)
}
