import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Service - CaseBreak AI",
  description: "CaseBreak AI Terms of Service. Read the full terms governing use of the CaseBreak AI platform.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b" id="terms-header">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="text-2xl font-bold text-blue-900">CaseBreak.AI</Link>
            <nav className="hidden md:flex items-center space-x-8" id="terms-nav">
              <Link href="/about" className="text-gray-600 hover:text-gray-900">About</Link>
              <Link href="/features" className="text-gray-600 hover:text-gray-900">Features</Link>
              <Link href="/pricing" className="text-gray-600 hover:text-gray-900">Pricing</Link>
              <Link href="/contact" className="text-gray-600 hover:text-gray-900">Contact</Link>
              <Link href="/sign-up" className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">Get Started</Link>
            </nav>
          </div>
        </div>
      </header>
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto prose prose-slate">
          <h1 id="terms-title">Terms of Service</h1>
          <p className="text-sm text-gray-500">Effective Date: March 20, 2026 | Last Updated: March 20, 2026</p>

          <h2>1. Agreement to Terms</h2>
          <p>By accessing or using CaseBreak AI (&ldquo;Service&rdquo;), operated by AI Venture Holdings LLC (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.</p>

          <h2>2. Description of Service</h2>
          <p>CaseBreak AI is an artificial intelligence-powered legal technology platform that provides case analysis, litigation simulation, document processing, and related analytical tools for legal professionals and organizations. The Service is designed to assist&mdash;not replace&mdash;qualified legal judgment.</p>
          <p><strong>Important Disclaimer:</strong> CaseBreak AI does not provide legal advice. All outputs, predictions, risk scores, recommendations, and analyses generated by the Service are informational tools only. They do not constitute legal advice or a substitute for consultation with a licensed attorney.</p>

          <h2>3. Eligibility</h2>
          <p>You must be at least 18 years of age and have the legal capacity to enter into a binding agreement. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>

          <h2>4. Account Registration and Security</h2>
          <p>You agree to provide accurate registration information, maintain the security of your login credentials, accept responsibility for all activities under your account, and notify us immediately of any unauthorized use.</p>

          <h2>5. Subscription Plans and Payment</h2>
          <p>Paid subscriptions are billed in advance via Stripe. Subscriptions automatically renew unless cancelled. You may cancel at any time through your account settings. Refund requests must be submitted within 14 days to support@casebreak.ai.</p>

          <h2>6. Acceptable Use</h2>
          <p>You may not use the Service for unlawful purposes, reverse-engineer the platform, use automated scraping tools without permission, misrepresent AI outputs as certified legal opinions, or submit third-party PII without legal basis. See our <Link href="/acceptable-use" className="text-blue-600">Acceptable Use Policy</Link> for full details.</p>

          <h2>7. Intellectual Property</h2>
          <p>The Service is owned by AI Venture Holdings LLC and protected by intellectual property laws. You retain ownership of content you upload. By uploading, you grant us a limited license to process your content solely to provide the Service.</p>

          <h2>8. Data Privacy</h2>
          <p>Your use is governed by our <Link href="/privacy" className="text-blue-600">Privacy Policy</Link>. We implement commercially reasonable security measures including encryption in transit and at rest.</p>

          <h2>9. Disclaimers</h2>
          <p><strong>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND.</strong> CaseBreak AI is an informational tool. It does not provide legal advice, create an attorney-client relationship, or serve as a substitute for a licensed attorney.</p>

          <h2>10. Limitation of Liability</h2>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, AI VENTURE HOLDINGS LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID IN THE TWELVE MONTHS PRECEDING THE CLAIM.</p>

          <h2>11. Governing Law</h2>
          <p>These Terms are governed by the laws of the State of Utah. Disputes shall be resolved through binding arbitration in Salt Lake City, Utah.</p>

          <h2>12. Contact</h2>
          <p>AI Venture Holdings LLC, Midvale, Utah, USA<br/>Email: legal@casebreak.ai</p>

          <p className="text-sm text-gray-500 mt-12 border-t pt-4">This document is for informational purposes. Consult a qualified attorney for legal advice specific to your situation.</p>
        </div>
      </main>
    </div>
  )
}
